haproxy:
  image: registry.internal.logz.io:5000/graphite-haproxy
  net: host
  environment:
    LINE_RELAY_LISTENERS: "relay1:2103,relay2:2203"
    PICKLE_RELAY_LISTENERS: "relay1:2104,relay2:2204"

relay1:
  image: registry.internal.logz.io:5000/carbon-relay
  ports:
    - "2103:2103"
    - "2104:2104"
  environment:
    LINE_RECEIVER_PORT: 2103
    PICKLE_RECEIVER_PORT: 2104
    RELAY_METHOD: consistent-hashing
    DESTINATIONS: cache1:2014:a1,cache2:2024:a2,cache3:2034:a3,cache4:2044:a4
  volumes: 
    - "~/logs/gaia/carbon/r/1:/var/log/carbon"
  links:
    - cache1
    - cache2
    - cache3
    - cache4

relay2:
  image: registry.internal.logz.io:5000/carbon-relay
  ports:
    - "2203:2203"
    - "2204:2204"
  environment:
    LINE_RECEIVER_PORT: 2203
    PICKLE_RECEIVER_PORT: 2204
    RELAY_METHOD: consistent-hashing
    DESTINATIONS: cache1:2014:a1,cache2:2024:a2,cache3:2034:a3,cache4:2044:a4
  volumes: 
    - "~/logs/gaia/carbon/r/2:/var/log/carbon"
  links:
    - cache1
    - cache2
    - cache3
    - cache4

cache1:
  image: registry.internal.logz.io:5000/carbon-cache
  volumes_from:
    - whisper
  volumes: 
    - "~/logs/gaia/carbon/c/1:/var/log/carbon"
  ports:
    - "7012:7012"
    - "2013:2013"
    - "2014:2014"
  environment:
    NODE_NAME: cache:a1
    LINE_RECEIVER_PORT: 2013
    PICKLE_RECEIVER_PORT: 2014
    CACHE_QUERY_PORT: 7012
    LOCAL_DATA_DIR: /opt/graphite/storage/whisper
  command: --instance=a1

cache2:
  image: registry.internal.logz.io:5000/carbon-cache
  volumes_from:
    - whisper
  volumes: 
    - "~/logs/gaia/carbon/c/2:/var/log/carbon"
  ports:
    - "7022:7022"
    - "2023:2023"
    - "2024:2024"
  environment:
    NODE_NAME: cache:a2
    LINE_RECEIVER_PORT: 2023
    PICKLE_RECEIVER_PORT: 2024
    CACHE_QUERY_PORT: 7022
    LOCAL_DATA_DIR: /opt/graphite/storage/whisper
  command: --instance=a2

cache3:
  image: registry.internal.logz.io:5000/carbon-cache
  volumes_from:
    - whisper
  volumes: 
    - "~/logs/gaia/carbon/c/3:/var/log/carbon"
  ports:
    - "7032:7032"
    - "2033:2033"
    - "2034:2034"
  environment:
    NODE_NAME: cache:a3
    LINE_RECEIVER_PORT: 2033
    PICKLE_RECEIVER_PORT: 2034
    CACHE_QUERY_PORT: 7032
    LOCAL_DATA_DIR: /opt/graphite/storage/whisper
  command: --instance=a3

cache4:
  image: registry.internal.logz.io:5000/carbon-cache
  volumes_from:
    - whisper
  volumes: 
    - "~/logs/gaia/carbon/c/4:/var/log/carbon"
  ports:
    - "7042:7042"
    - "2043:2043"
    - "2044:2044"
  environment:
    NODE_NAME: cache:a4
    LINE_RECEIVER_PORT: 2043
    PICKLE_RECEIVER_PORT: 2044
    CACHE_QUERY_PORT: 7042
    LOCAL_DATA_DIR: /opt/graphite/storage/whisper
  command: --instance=a4

web:
  image: registry.internal.logz.io:5000/graphite-web
  volumes_from:
    - whisper
  volumes: 
    - "~/logs/gaia/graphite:/var/log/graphite"
    - "~/logs/gaia/nginx:/var/log/nginx"
  environment:
    CARBONLINK_HOSTS: cache1:7012,cache2:7022,cache3:7032,cache4:7042
    WHISPER_DIR: /opt/graphite/storage/whisper
  ports:
    - "8080:80"
  links:
    - cache1
    - cache2
    - cache3
    - cache4

whisper:
  image: registry.internal.logz.io:5000/whisper
  volumes:
    - /Users/ofer_v/whisper:/opt/graphite/storage/whisper

